### ISSUE TITLE
Smaller feature requests

### ISSUE THREAD

**Issue by Sesa1988** [caduandrade/easy_table_flutter#16]
Hi,

I had some ideas and a smaller issue. 
Currently its not possible to let the table fill up the full height right?

- IsExpanded (fill available full height and width)
- Styling for header area
- Footer with paging
- Actionbar (would be nice to have only. Maybe a default widget where you can add actions like on appbar)

If it would be possible the actionbar on top and footer with paging would be even cooler.

**Comment by caduandrade** [comment]
Hi @Sesa1988 !

The table follows the layout constraints like any other Flutter widget ok? Or at least it should :-). So, the table will fill in height depending on your layout constraints. For example, if you put it inside an `Expanded` in `Column`, it will fill all the available height.

About the Footer and Actionbar, maybe you can do it yourself using your layout and controller. I still don't have an opinion on how much it's worth leaving this free for everyone to do on their own or if it's worth making the API more complex and providing something ready.

And about styling, I will do it soon.

**Comment by caduandrade** [comment]
@Sesa1988, I'm doing some customizations on #18 ok?

**Comment by Sesa1988** [comment]
> @Sesa1988, I'm doing some customizations on #18 ok?

@caduandrade okay, lets close this one then.
