### ISSUE TITLE
[Feature] OnLastItem

### ISSUE THREAD

**Issue by Sesa1988** [caduandrade/easy_table_flutter#20]
Hi,

It would be nice to have a callback when we rendered the last item. This would be useful for infinite scrolling.

Since we provide an item collection instead of a builder function its not that easy to implement. 
Only with workarounds like checking in every item onInit for index.

**Comment by caduandrade** [comment]
@Sesa1988, I understand that you would like to control given the index (the last one). In that case, maybe a listener that receives the index is better, don't you think? You could control it the way you want. For example, you could load the next page when 5 items are missing and not just the last one.

**Comment by Sesa1988** [comment]
> @Sesa1988, I understand that you would like to control given the index (the last one). In that case, maybe a listener that receives the index is better, don't you think? You could control it the way you want. For example, you could load the next page when 5 items are missing and not just the last one.

Do you mean like "onItemRendered(index)" on EasyTable? This would be probably better yes.

**Comment by caduandrade** [comment]
Final solution:

```dart
  Widget _table() {
    return EasyTable<String>(_model,
        onLastVisibleRowListener: _onLastVisibleRowListener);
  }

  void _onLastVisibleRowListener(int lastVisibleRowIndex) {
    if (lastVisibleRowIndex == _model!.visibleRowsLength - 1) {
      setState(() {
        _model!.addRow('value ${_model!.visibleRowsLength}');
      });
    }
  }
```

I got infinite scroll with that.
