### ISSUE TITLE
Flutter plugin files are missed when run "pub get"

### ISSUE THREAD

**Issue by MohamadNezar** [caduandrade/easy_table_flutter#26]
I didn't find easy_table_example directory in my flutter plugins directory when I installed this package.

**Comment by caduandrade** [comment]
Hi @MohamadNezar!

Sorry, I didn't quite understand the question. The example directory is `example` in the root of the package. 

Here, I can see it in IntelliJ: 

`... > .pub-cache > hosted > pub.darlang.org > easy_table-1.5.0 > example > lib > main.dart`
