### ISSUE TITLE
Feature Request - Add multiple column sort similar to what the JS dataTables library has

### ISSUE THREAD

**Issue by UNIcodeX** [caduandrade/easy_table_flutter#30]
Would it be possible to add sorting for multiple simultaneous columns? 

something like:
sort -> sub-sort -> sub-sort . 

I have a user who has requested this feature.

**Comment by UNIcodeX** [comment]
A number under the arrows would suffice probably. To the side may be better to avoid the header row jumping up and down in height.

DataTables library uses `SHIFT`, but `CTRL` may work. I could be wrong, but I believe `SHIFT` is the convention for Excel as well, and therefore more intuitive for the user.

There's an interactive demo on their front page if you want to get a feel for it.
https://www.datatables.net

**Comment by caduandrade** [comment]
I'm trying to figure out how to detect that CTRL/SHIFT is pressed while clicking on the header and the table is not in focus.

Didn't expect this :smile:

**Comment by caduandrade** [comment]
I think I'll release a version with just the `multiSortEnabled` parameter. Simple clicks without holding CTRL will configure the sort combination.
In a future version, if I figure out how to solve it, it could allow configuring a key holding to enable multi sort.

**Comment by UNIcodeX** [comment]
Excellent! Works perfectly. Thanks so much!!
