### ISSUE TITLE
Nesting support

### ISSUE THREAD

**Issue by bubnenkoff** [caduandrade/easy_table_flutter#34]
Hi! Thanks for your project. I have data that have 6 level of element nesting. Like:
```
Item:
 lots: 
   lot
     objs
         obj
```         

I need to display them in table. I did not seen tables components that have support of deep nesting. It would be cool if you will do something for this.

**Comment by caduandrade** [comment]
Hi @bubnenkoff . Tks.

Like an indentation inside the cell? Table tree?

I'm finishing testing the base for version 2.0. This will make these other improvements easier to make.

**Comment by bubnenkoff** [comment]
@caduandrade be honestly I do not know how to display data in better way. But I can show real data from my project that I need to display:
```
{
   "purchaseNumber": "03721000472342342053",
   "isGOZ": null,
   "docPublishDate": "2020-11-30T15:58:05.467+03:00",
   "responsibleOrg_inn": "7809016254",
   "responsibleOrg_regNum": "03721000476",
   "responsibleOrg_kpp": "783801001",
   "responsibleOrg_fullName": "Some very vary vary very looooooooooooooooooooooooooong naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaame hereeeeeeeeeeee", 
   "tag": "mytag",
   "region": "London",
   "xml_path": null,
   "lots": [
      {
         "lotNumber": null,
         "deliveryTerm": null,
         "currency_code": "USD",
         "lot_quantityUndefined": false,
         "contractGuarantee_procedureInfo": null,
         "contractGuarantee_amount": null,
         "lot_requirement_content": null,
         "objects": [
       
            {
               "object_code": 123,
               "object_name": "Apple 1",
               "quantity": "10000",
               "isMedicalProduct": null,
               "quantity_undeffined": null,
               "price": 574
            },
            {
               "object_code": 345,
               "object_name": "Apple 2",
               "quantity": "50000",
               "isMedicalProduct": null,
               "quantity_undeffined": null,
               "price": 852
            },
            {
               "object_code": 456,
               "object_name": "Apple 3",
               "quantity": "2500000",
               "isMedicalProduct": null,
               "quantity_undeffined": null,
               "price": 1000
            }

         ]
      }
   ],
   "customers": [
      {
         "customer_regNum": "03721000476",
         "customer_fullName": "Some org name"
      }
   ]
}
```

**Comment by caduandrade** [comment]
It's a little difficult to give an opinion as it depends on other UX factors such as whether any cell can be clicked or edited.

Maybe you need a table tree view and column groups at the same time (it's in my queue to be done).

**Comment by caduandrade** [comment]
So you weren't kidding when you said "nested" :smile: 

I think that kind of view would go against the table API. The most problematic would be the column settings. Soon I will make a column group but in your example, the values are nested. I think in this case, the best thing would be to create another package, especially for this kind of vision.

I think in the short term you can combine Row and Column.

I will close this issue ok?
