### ISSUE TITLE
Cell editing

### ISSUE THREAD

**Issue by shujaatak** [caduandrade/easy_table_flutter#35]

**Comment by caduandrade** [comment]
Hi @shujaatak! 

Yes sure. I'll still see that too. :+1:

**Comment by caduandrade** [comment]
Requires #38

**Comment by caduandrade** [comment]
With the bug fixes, it is possible to change the value of the line by creating a `TextField` and using the way you think is best (`onChanged` or `onFieldSubmitted`). I'll think better of how to provide a more automatic way of editing. It involves more details like validation, allowing icons, colors, etc.

Examples of cell builders:

```dart
EasyTableColumn(name: 'Name', cellBuilder: _cell)
```

```dart
  Widget _cell(BuildContext context, RowData<Person> data) {
    return TextFormField(
        initialValue: data.row.name,
        onChanged: (value) => data.row.name = value,
        decoration: const InputDecoration(
            contentPadding: EdgeInsets.zero,
            isDense: true,
            border: InputBorder.none));
  }
```

```dart
  Widget _cell(BuildContext context, RowData<Person> data) {
    return TextFormField(
        initialValue: data.row.name,
        onFieldSubmitted: (value) => data.row.name = value,
        decoration: const InputDecoration(
            contentPadding: EdgeInsets.zero,
            isDense: true,
            border: InputBorder.none));
  }
```

Keep in touch on any editing needs.

**Comment by shujaatak** [comment]
It would be so helpful to have a working example of cell editing in the repository if the feature has been implemented.
