### ISSUE TITLE
Suporte a Android e Ios

### ISSUE THREAD

**Issue by fanatico2020** [caduandrade/easy_table_flutter#45]
Olá, gostei do seu widget, mas vi que as rolagem scrool, não funciona no Android nem Ios, tem previsão de alguma atualização com isso?

**Comment by caduandrade** [comment]
Obrigado @fanatico2020 . Eu sequer testei ainda em celular pois o foco do pacote é Web/Desktop. Imagino que talvez seja a largura para o evento de toque ou algo assim. Estou terminando outras tarefas primeiro ok?

**Comment by fanatico2020** [comment]
massa, vou fica na expectativa. vlw

**Comment by caduandrade** [comment]
@fanatico2020 , fechando pois é o mesmo problema relatado na #48 ok?
