### ISSUE TITLE
rowsFit?

### ISSUE THREAD

**Issue by Taron133** [caduandrade/easy_table_flutter#49]
![image](https://user-images.githubusercontent.com/196996/183631594-8b42000d-8c69-48ca-9d5e-994ddd1a6f4b.png)

such as:
https://github.com/flutter/flutter/issues/70510

https://github.com/flutter/flutter/pull/102886

**Comment by caduandrade** [comment]
Hi @Taron133 ! 

I believe it is possible to have a function to be executed only once and manually. Otherwise, performance will drop drastically. For a larger amount of data, it is important that the height has a fixed size.

**Comment by Taron133** [comment]
Too bad the flutter table is inferior to the html table.
https://fiddle.sencha.com/#fiddle/1cd6&view/editor
![image](https://user-images.githubusercontent.com/196996/183640852-331167c7-9cac-4382-bf88-f708ea3ae636.png)

All grids/tables in flutter/pub.dev without height alignment for rows 8(
Has only Height for all rows as you talk.
