### ISSUE TITLE
Ability to customize hover cursor

### ISSUE THREAD

**Issue by ykrasik** [caduandrade/easy_table_flutter#57]
Hi @caduandrade :)

I'd like to request an ability to customize the hover cursor over a row when the row has gestures attached to it. It's currently [hardcoded to a "click" cursor](https://github.com/caduandrade/easy_table_flutter/blob/main/lib/src/internal/row_widget.dart#L122), which doesn't fit what I'm trying to achieve with it.

Thank you! 🔥 💪

**Comment by caduandrade** [comment]
Hi! 

It will be possible to configure a default cursor in the theme or define one for each row:

```dart
EasyTable<Person>(_model,
            onRowTap: (p) => print(p.name),
            rowCursor: (p) {
              if (p.index == 1) {
                return SystemMouseCursors.forbidden;
              }
              return null;
            })
```

Enough right?

**Comment by ykrasik** [comment]
Oh yeah, that sounds great. I assume returning `null` would mean 'no cursor', right? An alternative would be 'use default cursor' which would be the click cursor, but 'no cursor' sounds more intuitive.

BTW, what I was trying to do is add only a double tap listener on a row. On desktop, having it change to an action cursor felt unnatural.

**Comment by caduandrade** [comment]
By design, I'm keeping `NULL` to use the theme's default value. Similar to Flutter themes. But it's easy to remove the cursor in Flutter, just use `MouseCursor.defer`.

**Comment by ykrasik** [comment]
Awesome, thank you! 💪
